apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ssr-demo
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: __IMAGE__
